seed: 42
data:
  h5ad_path: data/labelled_data.h5ad
  max_len: 2134
  exclude_class: hGPC
  cluster_col: leiden_0.2_c6
model:
  vocab_size: null
  d_model: 128
  nhead: 4
  dim_feedforward: 256
  dropout: 0.1
  num_layers: 2
  num_classes: 7
training:
  batch_size: 128
  epochs: 100
  learning_rate_backbone: 0.000001
  learning_rate_head: 0.0001
  optimizer: adam
  loss: ldam
  split_ratio: 0.8
  pretrained_checkpoint_path: checkpoints/classifier/best_classifier.pth
  checkpoint_path: checkpoints/classifier/best_classifier_multi.pth
