seed: 42
data:
  h5ad_path: data/labelled_data.h5ad
  max_len: 2134
  exclude_class: hGPC
model:
  vocab_size: null
  d_model: 128
  nhead: 4
  dim_feedforward: 256
  dropout: 0.1
  num_layers: 2
  num_classes: 2
training:
  batch_size: 128
  epochs: 100
  learning_rate: 0.00001
  optimizer: adam
  loss: cross_entropy
  train_ratio: 0.70
  val_ratio: 0.15
  checkpoint_path: checkpoints/classifier/best_classifier.pth
